name: Evaluate a push or PR for issues

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, ready_for_review]

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # The default. Fetches the last commit that triggered the workflow
      - name: Evaluate a push or PR for issues
        uses: davecthomas/ghaprai@main
        id: log_pr_details # This ID is used to reference the output of this step
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display PR Files
        run: echo 'Files changed in the PR:' ${{ steps.log_pr_details.outputs.filesList }}

      - name: Display Diffs
        run: |
          echo 'Diffs for the changed files:' 
          echo '${{ steps.log_pr_details.outputs.encodedDiffs }}' | base64 --decode
