name: List Files in PR

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, ready_for_review]

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List files in the PR
        uses: davecthomas/ghaprai@main
        id: log_pr_details # This ID is used to reference the output of this step
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Display PR Files
        run: echo 'Files changed in the PR:' ${{ steps.log_pr_details.outputs.files }}
