name: Evaluate a push or PR for issues

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, ready_for_review]

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # The default. Fetches the last commit that triggered the workflow
      - name: Evaluate a push or PR for issues
        uses: davecthomas/ghaprai@main
        id: log_pr_details
        env: # Move OPENAI_API_KEY env here if it's used within this action
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Count Files
        run: echo 'Number of files changed:' ${{ steps.log_pr_details.outputs.countFiles }}

      - name: List Files
        run: echo 'Files changed:' ${{ steps.log_pr_details.outputs.filesList }}

      - name: Display Diffs
        run: |
          echo 'Diffs for the changed files:' 
          echo '${{ steps.log_pr_details.outputs.encodedDiffs }}' | base64 --decode
      - name: Run the AI 1
        run: |
          echo 'Running the AI on the changed files:' 
          echo '${{ steps.log_pr_details.outputs.openAiModels }}'
      - name: Run the AI 2
        run: |
          echo 'Running the AI on the changed files:' 
          echo '${{ steps.log_pr_details.outputs.openAiDiffResponse }}'
